
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class Currency : Luban.BeanBase
{
    public Currency(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["desc"].IsString) { throw new SerializationException(); }  Desc = _buf["desc"]; }
        { if(!_buf["itemName"].IsString) { throw new SerializationException(); }  ItemName = _buf["itemName"]; }
        { if(!_buf["itemText"].IsString) { throw new SerializationException(); }  ItemText = _buf["itemText"]; }
        { if(!_buf["itemExtraText"].IsString) { throw new SerializationException(); }  ItemExtraText = _buf["itemExtraText"]; }
        { if(!_buf["iconPic"].IsString) { throw new SerializationException(); }  IconPic = _buf["iconPic"]; }
        { if(!_buf["iconPicUi"].IsString) { throw new SerializationException(); }  IconPicUi = _buf["iconPicUi"]; }
    }

    public static Currency DeserializeCurrency(JSONNode _buf)
    {
        return new Currency(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 策划备注
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 货币名称
    /// </summary>
    public readonly string ItemName;
    /// <summary>
    /// 货币描述<br/>（用作货币的功能描述，必须填写）
    /// </summary>
    public readonly string ItemText;
    /// <summary>
    /// 货币额外的描述<br/>（用作货币背景描述，没有可不写）
    /// </summary>
    public readonly string ItemExtraText;
    /// <summary>
    /// 默认图标
    /// </summary>
    public readonly string IconPic;
    /// <summary>
    /// 默认界面小图标
    /// </summary>
    public readonly string IconPicUi;
   
    public const int __ID__ = 640046129;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "desc:" + Desc + ","
        + "itemName:" + ItemName + ","
        + "itemText:" + ItemText + ","
        + "itemExtraText:" + ItemExtraText + ","
        + "iconPic:" + IconPic + ","
        + "iconPicUi:" + IconPicUi + ","
        + "}";
    }
}
}

