
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class Item : Luban.BeanBase
{
    public Item(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["desc"].IsString) { throw new SerializationException(); }  Desc = _buf["desc"]; }
        { if(!_buf["itemName"].IsString) { throw new SerializationException(); }  ItemName = _buf["itemName"]; }
        { if(!_buf["itemText"].IsString) { throw new SerializationException(); }  ItemText = _buf["itemText"]; }
        { if(!_buf["itemExtraText"].IsString) { throw new SerializationException(); }  ItemExtraText = _buf["itemExtraText"]; }
        { if(!_buf["enumItemQuality"].IsNumber) { throw new SerializationException(); }  EnumItemQuality = (ItemQuality)_buf["enumItemQuality"].AsInt; }
    }

    public static Item DeserializeItem(JSONNode _buf)
    {
        return new Item(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 策划备注
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 道具名称
    /// </summary>
    public readonly string ItemName;
    /// <summary>
    /// 道具描述<br/>（用作道具功能描述，必须填写）
    /// </summary>
    public readonly string ItemText;
    /// <summary>
    /// 道具额外的描述<br/>（用作道具背景描述，没有可不写）
    /// </summary>
    public readonly string ItemExtraText;
    public readonly ItemQuality EnumItemQuality;
   
    public const int __ID__ = 2289459;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "desc:" + Desc + ","
        + "itemName:" + ItemName + ","
        + "itemText:" + ItemText + ","
        + "itemExtraText:" + ItemExtraText + ","
        + "enumItemQuality:" + EnumItemQuality + ","
        + "}";
    }
}
}

