
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum ItemQuality
    {
        /// <summary>
        /// 白色的
        /// </summary>
        White = 1,
        /// <summary>
        /// 黑色的
        /// </summary>
        Black = 2,
    }

} 

