
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TbCurrency
{
    private readonly System.Collections.Generic.Dictionary<int, Currency> _dataMap;
    private readonly System.Collections.Generic.List<Currency> _dataList;
    
    public TbCurrency(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, Currency>(count);
        _dataList = new System.Collections.Generic.List<Currency>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Currency _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.Currency.DeserializeCurrency(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Currency> DataMap => _dataMap;
    public System.Collections.Generic.List<Currency> DataList => _dataList;

    public Currency GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Currency Get(int key) => _dataMap[key];
    public Currency this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

